import os
import json
import base64
import requests
import glob
from pathlib import Path
from datetime import datetime
import re

def r2_request(method, path, data=None, content_type=None):
    worker_url = os.environ.get("VITE_R2_WORKER_URL")
    auth_token = os.environ.get("VITE_R2_AUTH_TOKEN")
    
    if not worker_url or not auth_token:
        print("Error: R2 environment variables missing")
        exit(1)
        
    baseUrl = worker_url if worker_url.endswith('/') else f"{worker_url}/"
    url = f"{baseUrl}{path}"
    
    headers = {
        "Authorization": f"Bearer {auth_token}"
    }
    if content_type:
        headers["Content-Type"] = content_type
        
    response = requests.request(method, url, headers=headers, data=data)
    if not response.ok and method != "DELETE":
        print(f"R2 Request Failed: {response.status_code} {response.text}")
        exit(1)
    return response

def clear_updates():
    print("Clearing asaas-updates/ in R2...")
    worker_url = os.environ.get("VITE_R2_WORKER_URL")
    auth_token = os.environ.get("VITE_R2_AUTH_TOKEN")
    
    if not worker_url or not auth_token:
        print("Error: R2 environment variables missing")
        return

    baseUrl = worker_url if worker_url.endswith('/') else f"{worker_url}/"
    list_url = f"{baseUrl}?list=1&prefix=asaas-updates/"
    
    headers = {"Authorization": f"Bearer {auth_token}"}
    response = requests.get(list_url, headers=headers)
    
    if response.ok:
        data = response.json()
        keys = data.get("keys", [])
        for key in keys:
            print(f"Deleting {key}...")
            r2_request("DELETE", key)
    else:
        print(f"Skip clearing: List failed (maybe empty or check worker)")

def upload_assets():
    print("Starting asset upload to R2...")
    # Broaden patterns to find assets wherever they might be in the bundle dir
    windows_patterns = [
        "src-tauri/target/release/bundle/msi/*.msi",
        "src-tauri/target/release/bundle/msi/*.msi.sig",
        "src-tauri/target/release/bundle/nsis/*.exe",
        "src-tauri/target/release/bundle/nsis/*.exe.sig",
        "src-tauri/target/release/bundle/updater/latest.json",
        "src-tauri/target/release/bundle/latest.json",
        "**/target/release/bundle/updater/latest.json"
    ]
    
    # Find Android assets
    android_patterns = [
        "src-tauri/gen/android/app/build/outputs/apk/universal/release/Asaas_*.apk",
        "src-tauri/gen/android/app/build/outputs/apk/debug/*.apk",
        "**/outputs/apk/**/Asaas_*.apk"
    ]
    
    all_files = []
    print("Searching for files using patterns...")
    for p in windows_patterns + android_patterns:
        matches = glob.glob(p, recursive=True)
        if matches:
            print(f"Pattern '{p}' matched: {matches}")
        all_files.extend(matches)
        
    if not all_files:
        print("No assets found to upload!")
        return

    # Fetch existing latest.json from R2 so we can merge
    remote_data = None
    worker_url = os.environ.get("VITE_R2_WORKER_URL")
    auth_token = os.environ.get("VITE_R2_AUTH_TOKEN")
    
    if worker_url and auth_token:
        baseUrl = worker_url if worker_url.endswith('/') else f"{worker_url}/"
        try:
            r2_url = f"{baseUrl}asaas-updates/latest.json"
            print(f"Attempting to fetch existing latest.json from {r2_url}")
            resp = requests.get(r2_url, headers={"Authorization": f"Bearer {auth_token}"})
            if resp.ok:
                remote_data = resp.json()
                print("Successfully fetched existing latest.json from R2")
            else:
                print(f"No existing latest.json found on R2 (status {resp.status_code})")
        except Exception as e:
            print(f"Error fetching existing latest.json: {e}")
    else:
        print("Error: R2 environment variables missing for latest.json processing")
        return

    # Determine version from tauri conf
    version = "0.0.0"
    try:
        with open("src-tauri/tauri.conf.json", 'r') as f:
            version = json.load(f).get("version", "0.0.0")
    except Exception as e:
        print(f"Warning: Could not read version from tauri.conf.json: {e}")

    # Preserve min_version from remote if it exists
    remote_min_version = remote_data.get("min_version", "0.0.0") if remote_data else "0.0.0"

    # Use remote data if it matches our version, else start fresh
    if remote_data and remote_data.get("version") == version:
        data = remote_data
    else:
        data = {
            "version": version,
            "notes": f"Release {version}",
            "pub_date": datetime.utcnow().isoformat() + "Z",
            "platforms": {}
        }

    # Always carry min_version forward
    data["min_version"] = data.get("min_version", remote_min_version)
        
    if "platforms" not in data:
        data["platforms"] = {}

    # Process local latest.json if generated by Tauri
    local_latest_json_path = None
    for f_path in all_files:
        if os.path.basename(f_path) == "latest.json":
            local_latest_json_path = f_path
            if "/updater/" in f_path:
                break
                
    if local_latest_json_path and os.path.exists(local_latest_json_path):
        print(f"Merging locally generated {local_latest_json_path}...")
        try:
            with open(local_latest_json_path, 'r') as f:
                local_data = json.load(f)
            # Merge its platforms
            for platform, details in local_data.get("platforms", {}).items():
                if "url" in details:
                    filename = os.path.basename(details["url"])
                    details["url"] = f"{baseUrl}asaas-updates/{filename}"
                    data["platforms"][platform] = details
                    print(f"Merged local platform rules: {platform}")
        except Exception as e:
            print(f"Error reading local latest.json: {e}")

    # Dynamically Map Windows if missing from local latest.json
    windows_bin = None
    for f_path in all_files:
        if f_path.endswith(".msi"):
            windows_bin = f_path
            break
        elif f_path.endswith(".exe") and not windows_bin:
            windows_bin = f_path
            
    if windows_bin and "windows-x86_64" not in data["platforms"]:
        sig_path = f"{windows_bin}.sig"
        signature = ""
        if os.path.exists(sig_path):
            try:
                with open(sig_path, 'r') as f: signature = f.read().strip()
            except: pass
        
        filename = os.path.basename(windows_bin)
        details = {
            "signature": signature,
            "url": f"{baseUrl}asaas-updates/{filename}"
        }
        data["platforms"]["windows-x86_64"] = details
        data["platforms"]["windows-x86_64-msi"] = details
        data["platforms"]["windows-x86_64-nsis"] = details
        print(f"Dynamically mapped windows platforms to {filename}")

    # Dynamically Map Android
    android_apk = None
    for f_path in all_files:
        basename = os.path.basename(f_path)
        if basename.startswith("Asaas_") and basename.endswith(".apk"):
            android_apk = f_path
            break
        elif f_path.endswith(".apk") and not android_apk:
            android_apk = f_path
            
    if android_apk:
        filename = os.path.basename(android_apk)
        details = {
            "signature": "",
            "url": f"{baseUrl}asaas-updates/{filename}"
        }
        for plat in ["android-aarch64", "android-armv7", "android-x86_64", "android-i686", "android"]:
            data["platforms"][plat] = details
        print(f"Dynamically mapped android platforms to {filename}")

    # Write merged JSON to disk
    final_latest_json = "latest.json"
    with open(final_latest_json, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"Generated final {final_latest_json} with platforms: {list(data.get('platforms', {}).keys())}")
    
    # Filter files for upload, ensuring we only upload the final latest.json
    files_to_upload = []
    if len(data.get("platforms", {})) > 0:
        files_to_upload.append(final_latest_json)
    else:
        print("Skipping latest.json upload because no platforms details were found")
        
    for f in all_files:
        if os.path.basename(f) == "latest.json":
            continue
        files_to_upload.append(f)

    # Upload all
    for file_path in files_to_upload:
        filename = os.path.basename(file_path)
        r2_path = f"asaas-updates/{filename}"
        print(f"Uploading {file_path} to {r2_path}...")
        
        content_type = "application/json" if filename.endswith(".json") else "application/octet-stream"
        if filename.endswith(".msi"): content_type = "application/x-msi"
        elif filename.endswith(".exe"): content_type = "application/x-msdos-program"
        elif filename.endswith(".apk"): content_type = "application/vnd.android.package-archive"
        
        with open(file_path, 'rb') as f:
            r2_request("PUT", r2_path, data=f, content_type=content_type)

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "clear":
        clear_updates()
    else:
        upload_assets()
