import type { AssistantCatalogEntry } from "./types";

export const assistantIntentCatalog: AssistantCatalogEntry[] = [
  {
    id: "revenue.thisMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "revenue.thisMonth",
    phrases: {
      en: ["revenue this month", "income this month", "sales this month"],
      ar: ["الايرادات هذا الشهر", "المبيعات هذا الشهر", "دخل هذا الشهر"],
      ku: ["داهاتی ئەم مانگە", "فرۆشتنی ئەم مانگە", "داهات ئەم مانگ"],
    },
  },
  {
    id: "revenue.today",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "revenue.today",
    phrases: {
      en: ["revenue today", "income today", "sales today"],
      ar: ["الايرادات اليوم", "المبيعات اليوم", "دخل اليوم"],
      ku: ["داهاتی ئەمڕۆ", "فرۆشتنی ئەمڕۆ", "داهات ئەمڕۆ"],
    },
  },
  {
    id: "revenue.thisYear",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "revenue.thisYear",
    phrases: {
      en: ["revenue this year", "income this year", "sales this year"],
      ar: ["الايرادات هذه السنة", "المبيعات هذه السنة", "دخل هذه السنة"],
      ku: ["داهاتی ئەم ساڵە", "فرۆشتنی ئەم ساڵە", "داهات ئەم ساڵ"],
    },
  },
  {
    id: "expenses.thisMonth",
    module: "Accounting",
    requiredFeature: "budget",
    requiredPermissions: ["budget.access"],
    handler: "expenses.thisMonth",
    phrases: {
      en: ["expenses this month", "costs this month", "what were my expenses"],
      ar: ["المصاريف هذا الشهر", "التكاليف هذا الشهر", "مصروفات هذا الشهر"],
      ku: ["خەرجی ئەم مانگە", "تێچووی ئەم مانگە", "مەسروفی ئەم مانگە"],
    },
  },
  {
    id: "profit.thisMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "profit.thisMonth",
    phrases: {
      en: ["profit this month", "net profit this month", "how much profit"],
      ar: ["الربح هذا الشهر", "صافي الربح هذا الشهر", "كم ربحنا هذا الشهر"],
      ku: ["قازانجی ئەم مانگە", "قازانج ئەم مانگ", "چەند قازانجمان کرد"],
    },
  },
  {
    id: "sales.countToday",
    module: "Sales History",
    requiredFeature: "sales_history",
    requiredPermissions: ["salesHistory.access"],
    handler: "sales.countToday",
    phrases: {
      en: ["how many sales today", "sales count today", "transactions today"],
      ar: ["عدد المبيعات اليوم", "كم عملية بيع اليوم", "كم فاتورة اليوم"],
      ku: ["چەند فرۆشتن ئەمڕۆ", "ژمارەی فرۆشتنی ئەمڕۆ", "چەند مامەڵە ئەمڕۆ"],
    },
  },
  {
    id: "invoices.unpaid",
    module: "Invoices History",
    requiredFeature: "invoices_history",
    requiredPermissions: ["invoiceHistory.access"],
    handler: "invoices.unpaid",
    phrases: {
      en: ["unpaid invoices", "open invoices", "invoices not paid"],
      ar: ["الفواتير غير المدفوعة", "فواتير مفتوحة", "فواتير لم تدفع"],
      ku: ["فاکتورە پارە نەدراوەکان", "فاکتوری کراوە", "فاکتور نەدراو"],
    },
  },
  {
    id: "receivables.total",
    module: "Payments",
    requiredFeature: "payments",
    requiredPermissions: ["payment.access"],
    handler: "receivables.total",
    phrases: {
      en: ["money owed to us", "receivables", "customers owe us"],
      ar: ["المبالغ المستحقة لنا", "كم لنا عند العملاء", "الذمم المدينة"],
      ku: ["پارەی قەرز لای کڕیاران", "چەند پارەمان لای خەڵکە", "پارەی پێمان"],
    },
  },
  {
    id: "payables.total",
    module: "Payments",
    requiredFeature: "payments",
    requiredPermissions: ["payment.access"],
    handler: "payables.total",
    phrases: {
      en: ["owe vendors", "payables", "how much do we owe suppliers"],
      ar: ["كم ندين للموردين", "الذمم الدائنة", "المستحق علينا"],
      ku: ["چەند قەرزمان لای فرۆشیارانە", "پارەی پێویستە بدەین", "قەرزی دابینکەران"],
    },
  },
  {
    id: "customers.topThisMonth",
    module: "Customers",
    requiredFeature: "crm",
    requiredPermissions: ["businessPartners.access"],
    handler: "customers.topThisMonth",
    phrases: {
      en: ["top customers this month", "best customers this month", "highest customers"],
      ar: ["افضل العملاء هذا الشهر", "اعلى العملاء هذا الشهر", "كبار العملاء"],
      ku: ["باشترین کڕیارەکانی ئەم مانگە", "زۆرترین کڕیار", "کڕیارە باڵاکان"],
    },
  },
  {
    id: "products.bestSellingThisMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "products.bestSellingThisMonth",
    phrases: {
      en: ["best selling products this month", "top products this month", "most sold products"],
      ar: ["المنتجات الاكثر مبيعا هذا الشهر", "افضل المنتجات هذا الشهر", "اكثر المنتجات مبيعا"],
      ku: ["باشترین کاڵا فرۆشراوەکانی ئەم مانگە", "زۆرترین کاڵای فرۆشراو", "کاڵا پرفرۆشەکان"],
    },
  },
  {
    id: "stock.low",
    module: "Products",
    requiredFeature: "products",
    requiredPermissions: ["products.access"],
    handler: "stock.low",
    phrases: {
      en: ["low stock", "products low in stock", "below minimum stock"],
      ar: ["المخزون المنخفض", "منتجات قليلة في المخزون", "اقل من الحد الادنى"],
      ku: ["کەمبوونی کۆگا", "کاڵای کەم لە کۆگا", "لە ژێر کەمترین ئاست"],
    },
  },
  {
    id: "stock.value",
    module: "Products",
    requiredFeature: "products",
    requiredPermissions: ["products.access"],
    handler: "stock.value",
    phrases: {
      en: ["current stock value", "inventory value", "stock worth"],
      ar: ["قيمة المخزون الحالية", "قيمة البضاعة", "كم قيمة المخزون"],
      ku: ["بەهای کۆگای ئێستا", "نرخی کۆگا", "بەهای کاڵاکان"],
    },
  },
  {
    id: "sales.byDayThisMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "sales.byDayThisMonth",
    phrases: {
      en: ["sales by day this month", "daily sales this month", "revenue by day"],
      ar: ["المبيعات حسب اليوم هذا الشهر", "المبيعات اليومية هذا الشهر", "الايرادات حسب اليوم"],
      ku: ["فرۆشتن بە ڕۆژ ئەم مانگە", "داهات بە ڕۆژ", "فرۆشتنی ڕۆژانە"],
    },
  },
  {
    id: "sales.byBranchThisMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "sales.byBranchThisMonth",
    phrases: {
      en: ["sales by branch this month", "branch sales this month", "revenue by branch"],
      ar: ["المبيعات حسب الفرع هذا الشهر", "ايرادات الفروع", "المبيعات لكل فرع"],
      ku: ["فرۆشتن بە لق ئەم مانگە", "داهات بە لق", "فرۆشتنی لقەکان"],
    },
  },
  {
    id: "purchases.thisMonth",
    module: "Orders",
    requiredFeature: "orders",
    requiredPermissions: ["orders.purchaseOrdersAccess"],
    handler: "purchases.thisMonth",
    phrases: {
      en: ["purchases this month", "purchase orders this month", "what did we buy this month"],
      ar: ["المشتريات هذا الشهر", "اوامر الشراء هذا الشهر", "ماذا اشترينا هذا الشهر"],
      ku: ["کڕینەکانی ئەم مانگە", "داواکاری کڕین ئەم مانگە", "چی کڕیوە ئەم مانگە"],
    },
  },
  {
    id: "invoices.overdue",
    module: "Payments",
    requiredFeature: "payments",
    requiredPermissions: ["payment.access"],
    handler: "invoices.overdue",
    phrases: {
      en: ["overdue invoices", "late invoices", "past due invoices"],
      ar: ["الفواتير المتأخرة", "فواتير متأخرة الدفع", "فواتير تجاوزت الاستحقاق"],
      ku: ["فاکتورە دواخراوەکان", "فاکتورە کاتی تێپەڕیوەکان", "فاکتوری دواکەوتوو"],
    },
  },
  {
    id: "ledger.cashReceivedToday",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.cashReceivedToday",
    phrases: {
      en: ["cash received today", "cash came in today", "received cash today"],
      ar: ["النقد المستلم اليوم", "كم كاش استلمنا اليوم", "الكاش الداخل اليوم"],
      ku: ["کاش وەرگیراوی ئەمڕۆ", "پارەی کاش ئەمڕۆ", "چەند کاش هاتووە ئەمڕۆ"],
    },
  },
  {
    id: "ledger.paidToday",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.paidToday",
    phrases: {
      en: ["how much did we pay today", "paid today", "money paid today"],
      ar: ["كم دفعنا اليوم", "المبالغ المدفوعة اليوم", "مدفوعات اليوم"],
      ku: ["چەندمان دا ئەمڕۆ", "پارەی دراو ئەمڕۆ", "پارەدانەکانی ئەمڕۆ"],
    },
  },
  {
    id: "metrics.compareMonth",
    module: "Revenue Analytics",
    requiredFeature: "net_revenue",
    requiredPermissions: ["revenueAnalytics.access"],
    handler: "metrics.compareMonth",
    phrases: {
      en: ["compare this month with last month", "this month vs last month", "month comparison"],
      ar: ["قارن هذا الشهر مع الشهر الماضي", "هذا الشهر مقابل الشهر الماضي", "مقارنة شهرية"],
      ku: ["ئەم مانگە بەراورد بکە لەگەڵ مانگی ڕابردوو", "ئەم مانگ بەرامبەر مانگی پێشوو", "بەراوردی مانگانە"],
    },
  },
  {
    id: "ledger.today",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.today",
    phrases: {
      en: ["today ledger", "show today's ledger", "ledger today"],
      ar: ["دفتر اليوم", "اعرض دفتر اليوم", "حركة اليوم"],
      ku: ["لەجەری ئەمڕۆ", "پیشانی لەجەری ئەمڕۆ بدە", "جوڵەی ئەمڕۆ"],
    },
  },
  {
    id: "ledger.moneyInToday",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.moneyInToday",
    phrases: {
      en: ["money came in today", "money in today", "inflow today"],
      ar: ["المال الداخل اليوم", "ما الذي دخل اليوم", "التدفق الداخل اليوم"],
      ku: ["پارەی هاتوو ئەمڕۆ", "پارە هاتە ژوور ئەمڕۆ", "داهاتی نەقدی ئەمڕۆ"],
    },
  },
  {
    id: "ledger.moneyOutToday",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.moneyOutToday",
    phrases: {
      en: ["money went out today", "money out today", "outflow today"],
      ar: ["المال الخارج اليوم", "ما الذي خرج اليوم", "التدفق الخارج اليوم"],
      ku: ["پارەی چوو دەرەوە ئەمڕۆ", "پارە دەرچوو ئەمڕۆ", "دەرچوونی پارە ئەمڕۆ"],
    },
  },
  {
    id: "ledger.partyTransactions",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.partyTransactions",
    phrases: {
      en: ["transactions for", "show transactions for", "customer transactions", "vendor transactions"],
      ar: ["حركات العميل", "حركات المورد", "معاملات", "اعرض معاملات"],
      ku: ["مامەڵەکانی", "جوڵەکانی", "پیشانی مامەڵەکانی", "بۆ"],
    },
  },
  {
    id: "ledger.byPaymentMethodThisMonth",
    module: "Ledger",
    requiredFeature: "ledger",
    requiredPermissions: ["ledger.access"],
    handler: "ledger.byPaymentMethodThisMonth",
    phrases: {
      en: ["ledger by payment method this month", "payment method this month", "cash fib qicard this month"],
      ar: ["الدفتر حسب طريقة الدفع هذا الشهر", "حسب وسيلة الدفع هذا الشهر", "الكاش والبطاقات هذا الشهر"],
      ku: ["لەجەر بە شێوازی پارەدان ئەم مانگە", "شێوازی پارەدان ئەم مانگە", "کاش و فاستپەی ئەم مانگە"],
    },
  },
];

export function getAssistantCatalogEntry(id: string | null) {
  return assistantIntentCatalog.find((entry) => entry.id === id);
}
