CREATE TABLE public.sale_return_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL,
  return_id uuid NOT NULL,
  sale_id uuid NOT NULL,
  sale_item_id uuid NOT NULL,
  quantity numeric NOT NULL,
  unit_refund_amount numeric NOT NULL DEFAULT 0,
  refund_amount numeric NOT NULL DEFAULT 0,
  restored_storage_id uuid NULL,
  restored_batch_allocations jsonb NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT sale_return_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT sale_return_items_unit_refund_amount_check CHECK (unit_refund_amount >= 0),
  CONSTRAINT sale_return_items_refund_amount_check CHECK (refund_amount >= 0),
  CONSTRAINT sale_return_items_return_sale_item_key UNIQUE (return_id, sale_item_id),
  PRIMARY KEY (id),
  FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  FOREIGN KEY (return_id) REFERENCES public.sale_returns(id),
  FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  FOREIGN KEY (sale_item_id) REFERENCES public.sale_items(id),
  FOREIGN KEY (restored_storage_id) REFERENCES public.storages(id)
);
