import {
  CreditCard,
  ArrowRightLeft,
  UsersRound,
  UserRound,
  Users,
  Truck,
  ShoppingCart,
  Store,
  FileSpreadsheet,
  FileText,
  HandCoins,
  Building2,
  Copy,
  Wallet,
  Boxes,
  History,
  Warehouse,
  Percent,
  Plane,
  BarChart3,
  TrendingUp,
  Globe,
  Undo2,
  CalendarClock,
  MapPinned,
  History as RouteHistory,
  Car,
  Link2,
} from "lucide-react";

export const WORKSPACE_PERMISSION_DEFINITIONS = [
  {
    key: "payment.access",
    module: "payment",
    labelKey: "members.permissions.paymentAccess",
    defaultLabel: "Payment module",
    descriptionKey: "members.permissions.paymentAccessDescription",
    defaultDescription: "Access the central payments page.",
    icon: CreditCard,
    section: "cash-and-control",
  },
  {
    key: "directTransaction.access",
    module: "directTransaction",
    labelKey: "members.permissions.directTransactionAccess",
    defaultLabel: "Direct Transaction module",
    descriptionKey: "members.permissions.directTransactionAccessDescription",
    defaultDescription: "Access manual incoming and outgoing transactions.",
    icon: ArrowRightLeft,
    section: "cash-and-control",
  },
  {
    key: "businessPartners.access",
    module: "businessPartners",
    labelKey: "members.permissions.businessPartnersAccess",
    defaultLabel: "Business Partners",
    descriptionKey: "members.permissions.businessPartnersAccessDescription",
    defaultDescription: "Access business partner records and balances.",
    icon: UsersRound,
    section: "partners-and-demand",
  },
  {
    key: "agents.access",
    module: "agents",
    labelKey: "members.permissions.agentsAccess",
    defaultLabel: "Agents",
    descriptionKey: "members.permissions.agentsAccessDescription",
    defaultDescription: "Access operational agents, drivers, territories, and linked workspace users.",
    icon: UserRound,
    section: "agents",
  },
  {
    key: "fleet.access",
    module: "fleet",
    labelKey: "members.permissions.fleetAccess",
    defaultLabel: "Fleet Management",
    descriptionKey: "members.permissions.fleetAccessDescription",
    defaultDescription: "Access fleet vehicles, assignments, and operational views.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "fleet.viewLiveLocations",
    module: "fleet",
    labelKey: "members.permissions.fleetViewLiveLocations",
    defaultLabel: "View live agent locations",
    descriptionKey: "members.permissions.fleetViewLiveLocationsDescription",
    defaultDescription: "View location-enabled agents on the live fleet map.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "fleet.viewHistory",
    module: "fleet",
    labelKey: "members.permissions.fleetViewHistory",
    defaultLabel: "View location history",
    descriptionKey: "members.permissions.fleetViewHistoryDescription",
    defaultDescription: "Review sampled agent movement history.",
    icon: RouteHistory,
    section: "agents",
  },
  {
    key: "fleet.manageVehicles",
    module: "fleet",
    labelKey: "members.permissions.fleetManageVehicles",
    defaultLabel: "Manage fleet vehicles",
    descriptionKey: "members.permissions.fleetManageVehiclesDescription",
    defaultDescription: "Create, update, and retire fleet vehicles.",
    icon: Car,
    section: "agents",
  },
  {
    key: "fleet.manageAssignments",
    module: "fleet",
    labelKey: "members.permissions.fleetManageAssignments",
    defaultLabel: "Manage vehicle assignments",
    descriptionKey: "members.permissions.fleetManageAssignmentsDescription",
    defaultDescription: "Assign vehicles to agents and end active assignments.",
    icon: Link2,
    section: "agents",
  },
  {
    key: "fleet.shareLocation",
    module: "fleet",
    labelKey: "members.permissions.fleetShareLocation",
    defaultLabel: "Share My Location",
    descriptionKey: "members.permissions.fleetShareLocationDescription",
    defaultDescription: "Share device location to track agent position in real time.",
    icon: MapPinned,
    section: "agents",
  },
  {
    key: "customers.access",
    module: "customers",
    labelKey: "members.permissions.customersAccess",
    defaultLabel: "Customers",
    descriptionKey: "members.permissions.customersAccessDescription",
    defaultDescription: "Access customer records and details.",
    icon: Users,
    section: "partners-and-demand",
  },
  {
    key: "suppliers.access",
    module: "suppliers",
    labelKey: "members.permissions.suppliersAccess",
    defaultLabel: "Suppliers",
    descriptionKey: "members.permissions.suppliersAccessDescription",
    defaultDescription: "Access supplier records and details.",
    icon: Truck,
    section: "partners-and-demand",
  },
  {
    key: "orders.saleOrdersAccess",
    module: "orders",
    labelKey: "members.permissions.saleOrdersAccess",
    defaultLabel: "Sale Order Access",
    descriptionKey: "members.permissions.saleOrdersAccessDescription",
    defaultDescription: "Access sales orders.",
    icon: ShoppingCart,
    section: "partners-and-demand",
  },
  {
    key: "orders.purchaseOrdersAccess",
    module: "orders",
    labelKey: "members.permissions.purchaseOrdersAccess",
    defaultLabel: "Purchase Order Access",
    descriptionKey: "members.permissions.purchaseOrdersAccessDescription",
    defaultDescription: "Access purchase orders.",
    icon: Truck,
    section: "partners-and-demand",
  },
  {
    key: "ecommerce.access",
    module: "ecommerce",
    labelKey: "members.permissions.ecommerceAccess",
    defaultLabel: "E-Commerce",
    descriptionKey: "members.permissions.ecommerceAccessDescription",
    defaultDescription: "Access marketplace orders and e-commerce operations.",
    icon: Store,
    section: "partners-and-demand",
  },
  {
    key: "accounting.access",
    module: "accounting",
    labelKey: "members.permissions.accountingAccess",
    defaultLabel: "Accounting",
    descriptionKey: "members.permissions.accountingAccessDescription",
    defaultDescription: "Access accounting records and budget controls.",
    icon: FileSpreadsheet,
    section: "cash-and-control",
  },
  {
    key: "invoiceHistory.access",
    module: "invoiceHistory",
    labelKey: "members.permissions.invoiceHistoryAccess",
    defaultLabel: "Invoice History & Upload Files",
    descriptionKey: "members.permissions.invoiceHistoryAccessDescription",
    defaultDescription: "Access invoice history and uploaded invoice files.",
    icon: FileText,
    section: "cash-and-control",
  },
  {
    key: "loans.access",
    module: "loans",
    labelKey: "members.permissions.loansAccess",
    defaultLabel: "Loans",
    descriptionKey: "members.permissions.loansAccessDescription",
    defaultDescription: "Access loan records and histories.",
    icon: HandCoins,
    section: "cash-and-control",
  },
  {
    key: "realEstate.access",
    module: "realEstate",
    labelKey: "members.permissions.realEstateAccess",
    defaultLabel: "Real Estate",
    descriptionKey: "members.permissions.realEstateAccessDescription",
    defaultDescription: "Access property transactions, balances, and installment schedules.",
    icon: Building2,
    section: "real-estate",
  },
  {
    key: "currencyExchange.access",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeAccess",
    defaultLabel: "Currency Exchange Service",
    descriptionKey: "members.permissions.currencyExchangeAccessDescription",
    defaultDescription: "Access walk-in currency exchange transaction creation and history.",
    icon: ArrowRightLeft,
    section: "currency-exchange",
  },
  {
    key: "currencyExchangeFeeRules.access",
    module: "currencyExchangeFeeRules",
    labelKey: "members.permissions.currencyExchangeFeeRulesAccess",
    defaultLabel: "Fee/Commission Rules",
    descriptionKey: "members.permissions.currencyExchangeFeeRulesAccessDescription",
    defaultDescription: "Access reusable currency exchange fee and commission rules.",
    icon: Percent,
    section: "currency-exchange",
  },
  {
    key: "currencyExchange.managePrices",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeManagePrices",
    defaultLabel: "Manage FX Prices",
    descriptionKey: "members.permissions.currencyExchangeManagePricesDescription",
    defaultDescription: "Edit manual buy and sell prices for currency exchange pairs.",
    icon: TrendingUp,
    section: "currency-exchange",
  },
  {
    key: "currencyExchange.reverse",
    module: "currencyExchange",
    labelKey: "members.permissions.currencyExchangeReverse",
    defaultLabel: "Reverse Transactions",
    descriptionKey: "members.permissions.currencyExchangeReverseDescription",
    defaultDescription: "Allows reversing exchange transactions, restoring safe balances to their prior state.",
    icon: Undo2,
    section: "currency-exchange",
  },
  {
    key: "travelAgency.access",
    module: "travelAgency",
    labelKey: "members.permissions.travelAgencyAccess",
    defaultLabel: "Travel Agency",
    descriptionKey: "members.permissions.travelAgencyAccessDescription",
    defaultDescription: "Access travel agency bookings, sales, and payments.",
    icon: Plane,
    section: "sell-and-serve",
  },
  {
    key: "clinicalAppointments.access",
    module: "clinicalAppointments",
    labelKey: "members.permissions.clinicalAppointmentsAccess",
    defaultLabel: "Clinical Appointments",
    descriptionKey: "members.permissions.clinicalAppointmentsAccessDescription",
    defaultDescription: "Access clinical appointments module.",
    icon: CalendarClock,
    section: "clinic-service",
  },
  {
    key: "clinicalPatients.access",
    module: "clinicalPatients",
    labelKey: "members.permissions.clinicalPatientsAccess",
    defaultLabel: "Patients",
    descriptionKey: "members.permissions.clinicalPatientsAccessDescription",
    defaultDescription: "Access patient records and details.",
    icon: Users,
    section: "clinic-service",
  },
  {
    key: "installments.access",
    module: "installments",
    labelKey: "members.permissions.installmentsAccess",
    defaultLabel: "Installments",
    descriptionKey: "members.permissions.installmentsAccessDescription",
    defaultDescription: "Access installment schedules and collection flow.",
    icon: Copy,
    section: "cash-and-control",
  },
  {
    key: "ledger.access",
    module: "ledger",
    labelKey: "members.permissions.ledgerAccess",
    defaultLabel: "Ledger",
    descriptionKey: "members.permissions.ledgerAccessDescription",
    defaultDescription: "Access ledger and cross-module financial trails.",
    icon: Wallet,
    section: "cash-and-control",
  },
  {
    key: "stockAdjustments.access",
    module: "stockAdjustments",
    labelKey: "members.permissions.stockAdjustmentsAccess",
    defaultLabel: "Stock Adjustments",
    descriptionKey: "members.permissions.stockAdjustmentsAccessDescription",
    defaultDescription: "Access stock adjustment records.",
    icon: Boxes,
    section: "stock-and-supply",
  },
  {
    key: "inventoryTransactions.access",
    module: "inventoryTransactions",
    labelKey: "members.permissions.inventoryTransactionsAccess",
    defaultLabel: "Inventory Transactions",
    descriptionKey: "members.permissions.inventoryTransactionsAccessDescription",
    defaultDescription: "Access inventory movement and transaction logs.",
    icon: History,
    section: "stock-and-supply",
  },
  {
    key: "inventoryTransfer.access",
    module: "inventoryTransfer",
    labelKey: "members.permissions.inventoryTransferAccess",
    defaultLabel: "Inventory Transfer",
    descriptionKey: "members.permissions.inventoryTransferAccessDescription",
    defaultDescription: "Access inventory transfer workflows.",
    icon: ArrowRightLeft,
    section: "stock-and-supply",
  },
  {
    key: "storages.access",
    module: "storages",
    labelKey: "members.permissions.storagesAccess",
    defaultLabel: "Storages",
    descriptionKey: "members.permissions.storagesAccessDescription",
    defaultDescription: "Access warehouses and storage locations.",
    icon: Warehouse,
    section: "stock-and-supply",
  },
  {
    key: "discounts.access",
    module: "discounts",
    labelKey: "members.permissions.discountsAccess",
    defaultLabel: "Discounts",
    descriptionKey: "members.permissions.discountsAccessDescription",
    defaultDescription: "Access discount and promotion controls.",
    icon: Percent,
    section: "stock-and-supply",
  },
  {
    key: "revenueAnalytics.access",
    module: "revenueAnalytics",
    labelKey: "members.permissions.revenueAnalyticsAccess",
    defaultLabel: "Revenue Analytics",
    descriptionKey: "members.permissions.revenueAnalyticsAccessDescription",
    defaultDescription: "Access revenue analytics and reporting.",
    icon: BarChart3,
    section: "insights-and-trends",
  },
  {
    key: "teamPerformance.access",
    module: "teamPerformance",
    labelKey: "members.permissions.teamPerformanceAccess",
    defaultLabel: "Team Performance",
    descriptionKey: "members.permissions.teamPerformanceAccessDescription",
    defaultDescription: "Access team performance reporting.",
    icon: TrendingUp,
    section: "people-and-workspace",
  },
  {
    key: "hr.access",
    module: "hr",
    labelKey: "members.permissions.hrAccess",
    defaultLabel: "HR",
    descriptionKey: "members.permissions.hrAccessDescription",
    defaultDescription: "Access HR records and workflows.",
    icon: UsersRound,
    section: "people-and-workspace",
  },
  {
    key: "global.NOprint",
    module: "global",
    labelKey: "members.permissions.globalPrint",
    defaultLabel: "Print",
    descriptionKey: "members.permissions.globalPrintDescription",
    defaultDescription: "Allow printing across all modules by default.",
    icon: Globe,
    section: "global",
  },
  {
    key: "manualEntry.access",
    module: "manualEntry",
    labelKey: "members.permissions.manualEntryAccess",
    defaultLabel: "Manual Entry",
    descriptionKey: "members.permissions.manualEntryAccessDescription",
    defaultDescription: "Access manual entry creation and history.",
    icon: FileText,
    section: "manual-entry",
  },
  {
    key: "manualEntryTemplates.access",
    module: "manualEntryTemplates",
    labelKey: "members.permissions.manualEntryTemplatesAccess",
    defaultLabel: "Manual Entry Templates",
    descriptionKey: "members.permissions.manualEntryTemplatesAccessDescription",
    defaultDescription: "Access manual entry template management.",
    icon: FileSpreadsheet,
    section: "manual-entry",
  },
  {
    key: "pos.access",
    module: "pos",
    labelKey: "members.permissions.posAccess",
    defaultLabel: "POS",
    descriptionKey: "members.permissions.posAccessDescription",
    defaultDescription: "Access the point-of-sale checkout flow.",
    icon: CreditCard,
    section: "sell-and-serve",
  },
  {
    key: "instantPos.access",
    module: "instantPos",
    labelKey: "members.permissions.instantPosAccess",
    defaultLabel: "Instant POS",
    descriptionKey: "members.permissions.instantPosAccessDescription",
    defaultDescription: "Access the rapid-service fast lane POS.",
    icon: ArrowRightLeft,
    section: "sell-and-serve",
  },
  {
    key: "salesHistory.access",
    module: "salesHistory",
    labelKey: "members.permissions.salesHistoryAccess",
    defaultLabel: "Sales History",
    descriptionKey: "members.permissions.salesHistoryAccessDescription",
    defaultDescription: "Access completed sales, returns, and sales records.",
    icon: History,
    section: "sell-and-serve",
  },
  {
    key: "products.access",
    module: "products",
    labelKey: "members.permissions.productsAccess",
    defaultLabel: "Products",
    descriptionKey: "members.permissions.productsAccessDescription",
    defaultDescription: "Access the product catalog, stock rules, and pricing.",
    icon: ShoppingCart,
    section: "stock-and-supply",
  },
  {
    key: "budget.access",
    module: "budget",
    labelKey: "members.permissions.budgetAccess",
    defaultLabel: "Budget",
    descriptionKey: "members.permissions.budgetAccessDescription",
    defaultDescription: "Access accounting records, budgets, and financial controls.",
    icon: Wallet,
    section: "cash-and-control",
  },
] as const;

export type WorkspacePermissionKey =
  (typeof WORKSPACE_PERMISSION_DEFINITIONS)[number]["key"];

const supportedPermissionKeys = new Set<string>(
  WORKSPACE_PERMISSION_DEFINITIONS.map((permission) => permission.key),
);

export function isSupportedWorkspacePermissionKey(
  key: string,
): key is WorkspacePermissionKey {
  return supportedPermissionKeys.has(key);
}

export function getWorkspacePermissionModule(key: string) {
  return key.split(".")[0] || key;
}
